import type { FindingCategory, Priority } from "../domain";
import type { StationDescription } from "../station/schema";

/** Minimal structural type for TipTap/ProseMirror JSON (server-safe). */
export type TiptapMark = { type: string; attrs?: Record<string, unknown> };
export type TiptapNode = {
  type: string;
  attrs?: Record<string, unknown>;
  content?: TiptapNode[];
  text?: string;
  marks?: TiptapMark[];
};
export type TiptapDoc = { type: "doc"; content: TiptapNode[] };

export type KeyPoint = {
  id: string;
  title: string;
  description: string;
  priority: Priority;
  category: FindingCategory;
  findingIds: string[];
  captureIds: string[];
  source: "ai" | "handmatig";
  accepted: boolean;
};

export type OpenQuestion = {
  id: string;
  question: string;
  answer: string | null;
  resolved: boolean;
};

export type SectionState = {
  key: string;
  title: string;
  /** Hash of the section content as last generated by AI (null = never AI). */
  aiHash: string | null;
  generatedAt: string | null;
};

export type ReportMeta = {
  keyPoints: KeyPoint[];
  openQuestions: OpenQuestion[];
  sections: Record<string, SectionState>;
  generatedBy: { jobId: string | null; model: string; at: string } | null;
  /** Station description proposed by AI, applied to station_descriptions. */
  station?: StationDescription | null;
  /** Findings grouping used in the report. */
  findingsGrouping?: "thema" | "locatie";
};

/**
 * Report section keys used by the standard layout (10.2). The cover page is
 * rendered from inspection metadata and is not part of the document.
 */
export const STANDARD_SECTIONS = [
  { key: "samenvatting", title: "Samenvatting" },
  { key: "doel_scope", title: "Doel en scope" },
  { key: "overzichtskaart", title: "Overzichtskaart" },
  { key: "bevindingen", title: "Bevindingen" },
  { key: "station", title: "Stationsbeschrijving" },
  { key: "afrekening", title: "Afrekenonderbouwing" },
  { key: "actiepunten", title: "Actiepunten" },
  { key: "checklist", title: "Checklist" },
  { key: "bijlagen", title: "Bijlagen" },
] as const;
export type StandardSectionKey = (typeof STANDARD_SECTIONS)[number]["key"];

export function emptyReportMeta(): ReportMeta {
  return { keyPoints: [], openQuestions: [], sections: {}, generatedBy: null };
}
